"""create market_prices

Revision ID: edd3c1855e95
Revises: 
Create Date: 2025-12-26 07:27:23.945689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd3c1855e95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('mandi', sa.String(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_prices')
    # ### end Alembic commands ###
