// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwM3-4lUNkhP8McDdjYmgN77MtBBxwNo',
    appId: '1:322919516706:web:c7b9eb94da39b8b1ccd87b',
    messagingSenderId: '322919516706',
    projectId: 'agri-auth-43b07',
    authDomain: 'agri-auth-43b07.firebaseapp.com',
    storageBucket: 'agri-auth-43b07.firebasestorage.app',
    measurementId: 'G-H053RKXCS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGf740279xY4ZEz91soAf0g1s2VpX6SBI',
    appId: '1:322919516706:android:744fb938b8efaf9cccd87b',
    messagingSenderId: '322919516706',
    projectId: 'agri-auth-43b07',
    storageBucket: 'agri-auth-43b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItW3n_ycOFHMzr6L_1GlCDfVE1hCdEk8',
    appId: '1:322919516706:ios:66600ee66d3a082eccd87b',
    messagingSenderId: '322919516706',
    projectId: 'agri-auth-43b07',
    storageBucket: 'agri-auth-43b07.firebasestorage.app',
    iosBundleId: 'com.example.agriPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItW3n_ycOFHMzr6L_1GlCDfVE1hCdEk8',
    appId: '1:322919516706:ios:66600ee66d3a082eccd87b',
    messagingSenderId: '322919516706',
    projectId: 'agri-auth-43b07',
    storageBucket: 'agri-auth-43b07.firebasestorage.app',
    iosBundleId: 'com.example.agriPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIwM3-4lUNkhP8McDdjYmgN77MtBBxwNo',
    appId: '1:322919516706:web:177cc980cfb7ccfeccd87b',
    messagingSenderId: '322919516706',
    projectId: 'agri-auth-43b07',
    authDomain: 'agri-auth-43b07.firebaseapp.com',
    storageBucket: 'agri-auth-43b07.firebasestorage.app',
    measurementId: 'G-FGX92707F7',
  );

}